//completely independent
import './methods/debounce.js';
import './methods/deferrable.js';
import './methods/memoize.js';
import './methods/memoizeFifo.js';
import './methods/memoizeLfu.js';
import './methods/memoizeLru.js';
import './methods/throttle.js';
import './static/isAsync.js';